name: PlatformIO CI

on: [push, pull_request]

jobs:
  platformio-build:
    runs-on: ubuntu-latest
    container: infinitecoding/platformio-for-ci:latest

    steps:
      - uses: actions/checkout@v2

      - name: Check PlatformIO version
        run: pio --version

      - name: Install platform
        run: pio platform install espressif8266

      - name: Build firmware
        run: pio run -d . -e esp12e

      - name: Upload firware artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.elf
          path: example/.pio/build/esp12e/firmware.elf
